# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumuser',
            old_name='orguser',
            new_name='user',
        ),
    ]
