# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0002_auto_20181101_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumuser',
            name='f1',
            field=models.CharField(max_length=100, null=True, verbose_name='Ful Nam'),
        ),
    ]
