# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0006_auto_20181130_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumuser',
            name='SpoNam',
            field=models.CharField(max_length=20, null=True, verbose_name='Spouse Name'),
        ),
        migrations.AlterField(
            model_name='dumuser',
            name='dadNam',
            field=models.CharField(max_length=20, null=True, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='dumuser',
            name='momNam',
            field=models.CharField(max_length=20, null=True, verbose_name='Mother Name'),
        ),
    ]
