# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0007_auto_20181130_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumuser',
            name='homea1',
            field=models.CharField(help_text='ln2', max_length=100, null=True, verbose_name='ln1'),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='homea2',
            field=models.CharField(max_length=100, null=True, verbose_name='ln2'),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='homea3',
            field=models.CharField(help_text='Village, Thana and District', max_length=100, null=True, verbose_name='ln3'),
        ),
    ]
