# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0008_auto_20181201_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumuser',
            name='homea1',
            field=models.CharField(max_length=100, null=True, verbose_name='home Address Line 1'),
        ),
        migrations.AlterField(
            model_name='dumuser',
            name='homea2',
            field=models.CharField(max_length=100, null=True, verbose_name='home Address Line 3'),
        ),
        migrations.AlterField(
            model_name='dumuser',
            name='homea3',
            field=models.CharField(max_length=100, null=True, verbose_name='home Address Line 2'),
        ),
    ]
