# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0010_auto_20181201_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumuser',
            name='Addr',
            field=models.CharField(help_text='Present Address', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='contactNo',
            field=models.CharField(max_length=14, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='withEffectFrom',
            field=models.DateField(null=True, verbose_name='With Effect From'),
        ),
        migrations.AlterField(
            model_name='dumuser',
            name='TodayDate',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Today Date '),
        ),
    ]
