# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duminfo', '0011_auto_20181201_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumuser',
            name='EmercontactNo',
            field=models.CharField(help_text='Mobile / Telephone Number', max_length=14, null=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='IDAddChoice',
            field=models.CharField(choices=[('Permanent Address', 'Permanent Address'), ('Present Address', 'Present Address'), ('Both', 'Both')], default='Both', max_length=25, null=True, verbose_name='Which Address to choose in id Card '),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='IDName',
            field=models.CharField(max_length=40, null=True, verbose_name='Name to be displayed on ID Card'),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='bloodgrp',
            field=models.CharField(help_text='AB+/O-', max_length=20, null=True, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='dumuser',
            name='contactNo',
            field=models.CharField(help_text='Mobile / Telephone Number', max_length=14, null=True, verbose_name='Contact Number'),
        ),
    ]
