from django.contrib.admin.widgets import AdminDateWidget
from django import forms

necdict = {1: ('f1',
               'f3',
               'f4'),
           2: ('f1',
               'f2',
               'f6'),
           3: ('fullName',
               'dob',
               'post',
               'dept',
               'relievingOrNo',
               'relDate',
               'relDate',
               'dateOfJoin',
               'AddrLine1',
               'AddrLine2',
               'AddrLine3',
               'dateOfJoin',
               'timeOfJoin',
               'TodayDate'
               ),
           4: ('fullName',
               'dept',
               'post',
               'pcRec',
               'JustifOsSw',
               'ProxyReq',
               'dummyChar1',
               'dummyChar2',
               'dummyChar3',
               'EmpNo',
               'TodayDate'
               ),
           5: ('fullName',
               'post',
               'dept',
               'AsShares',
               'AsMov',
               'AdDebt',
               'remarks',
               'TodayDate',
               'EmpNo'),
           6: ('LName',
               'FName',
               'AddrLine1',
               'AddrLine2',
               'AddrLine3',
               'homea1',
               'homea2',
               'homea3',
               'PakAdL1',
               'PakAdL2',
               'PakAdL3',
               'dadNam',
               'Dadnat',
               'pbDad',
               'dadDesigAddr',
               'dadAddr',
               'dadPermAddr',
               'momNam',
               'Momnat',
               'pbMom',
               'MomDesigAddr',
               'MomAddr',
               'MomPermAddr',
               'SpoNam',
               'Sponat',
               'pbSpof',
               'SpoDesigAddr',
               'SpoAddr',
               'SpoPermAddr',
               'Natlty',
               'dob',
               'age',
               'clsXage',
               'birthPlace',
               'birthdistrict',
               'fatherDistrict',
               'religion',
               'ScSt',
               'scstName',
               'arrested',
               'prosecuted',
               'detention',
               'boundDown',
               'fined',
               'convicted',
               'debarUniv',
               'debatPubSer',
               'pendCourt',
               'pendUniv',
               'crimeDesc',
               'localityRef1',
               'localityRef2',
               'place',
               ),
           7: ('fullName',
               'post',
               'dept',
               'dob',
               'Addr',
               'contactNo',
               'dateOfJoin',
               'withEffectFrom',
               'TodayDate',
               ),
           8: ('fullName',
               'EmpNo',
               'IDName',
               'post',
               'dept',
               'dob',
               'bloodgrp',
               'AddrLine1',
               'AddrLine2',
               'AddrLine3',
               'homea1',
               'homea2',
               'homea3',
               'IDAddChoice',
               'contactNo',
               'EmercontactNo',
               'TodayDate',
               ),

           }
widgetDict = {'f4': forms.DateInput(attrs={'class': 'date-input'}),
              'f6': forms.DateTimeInput(attrs={'class': 'date-input'}),
              'TodayDate': forms.DateInput(attrs={'class': 'date-input'}),
              'dateOfJoin': forms.DateInput(attrs={'class': 'date-input'}),
              'relDate': forms.DateInput(attrs={'class': 'date-input'}),
              'dob': forms.DateInput(attrs={'class': 'date-input'}),
              'withEffectFrom': forms.DateInput(attrs={'class': 'date-input'}),
              }

formPhDict = {
    'f1': '++name++',
    'f2': '++email++',
    'f3': '++email++',
    'f4': '++date++',
    'f5': '++email++',
    'f6': '++date++',
    'ProxyReq': '+++ProxyReq+++',
    'AdDebt': '+++AdDebt+++',
    'AsShares': '+++AsShares+++',
    'localityRef2': '+++localityRef2+++',
    'dadPermAddr': '+++dadPermAddr+++',
    'place': '+++place+++',
    'dept': '+++dept+++',
    'Sponat': '+++Sponat+++',
    'pbMom': '++pbMom+++',
    'fined': '+++fined+++',
    'dob': '+++dob+++',
    'relievingOrNo': '+++relievingOrNo+++',
    'HAdLn1': '+++HAdLn1+++',
    'HAdLn2': '+++HAdLn2+++',
    'HAdLn3': '+++HAdLn3+++',
    'homea1': '+++homea1+++',
    'homea2': '+++homea2+++',
    'homea3': '+++homea3+++',
    'dummyChar3': '+++dummyChar3+++',
    'scstName': '+++scstName+++',
    'FName': '+++firName+++',
    'dadAddr': '+++dadAddr+++',
    'Dadnat': '+++Dadnat+++',
    'convicted': '+++convicted+++',
    'PakAdL1': '+++PakAdL1+++',
    'dadDesigAddr': '+++dadDesigAddr+++',
    'fullName': '+++fullName+++',
    'pendUniv': '+++pendUniv+++',
    'AddrLine1': '+++AddrLine1+++',
    'localityRef1': '+++localityRef1+++',
    'PakAdL3': '+++PakAdL3+++',
    'arrested': '+++arrested+++',
    'timeOfJoin': '+++timeOfJoin+++',
    'relDate': '+++relDate+++',
    'prosecuted': '+++prosecuted+++',
    'clsXage': '+++clsXage+++',
    'pbDad': '++pbDad+++',
    'dummyChar2': '+++dummyChar2+++',
    'JustifOsSw': '+++JustifOsSw+++',
    'debatPubSer': '+++debatPubSer+++',
    'PakAdL2': '+++PakAdL2+++',
    'pbSpof': '++pbSpof+++',
    'MomPermAddr': '+++MomPermAddr+++',
    'post': '+++post+++',
    'TodayDate ': '+++TodayDate+++ ',
    'SpoNam': '+++SpoNam+++',
    'SpoPermAddr': '+++SpoPermAddr+++',
    'momNam': '+++momNam+++',
    'pcRec': '+++pcRec+++',
    'MomAddr': '+++MomAddr+++',
    'boundDown': '+++boundDown+++',
    'ScSt': '+++ScSt+++',
    'SpoDesigAddr': '+++SpoDesigAddr+++',
    'EmpNo': '+++EmpNo+++',
    'religion': '+++religion+++',
    'LName': '+++lasName+++',
    'SpoAddr': '+++SpoAddr+++',
    'detention': '+++detention+++',
    'AsMov': '+++AsMov+++',
    'AddrLine3': '+++AddrLine3+++',
    'remarks': '+++remarks+++',
    'dummyChar1': '+++dummyChar1+++',
    'pendCourt': '+++pendCourt+++',
    'age': '+++age+++',
    'AddrLine2': '+++AddrLine2+++',
    'fatherDistrict': '+++fatherDistrict+++',
    'Momnat': '+++Momnat+++',
    'MomDesigAddr': '+++MomDesigAddr+++',
    'crimeDesc': '+++crimeDesc+++',
    'TodayDate': '+++TodayDate+++',
    'Natlty': '+++Natlty+++',
    'dadNam': '+++dadNam+++',
    'dateOfJoin': '+++dateOfJoin+++',
    'birthdistrict': '+++birthdistrict+++',
    'birthPlace': '+++birthPlace+++',
    'debarUniv': '+++debarUniv+++',
    'Addr': '+++Addr+++',
    'contactNo': '+++contactNo+++',
    'withEffectFrom': '+++withEffectFrom+++',
    'IDAddChoice': '+++IDAddChoice+++',
    'IDName': '+++IDName+++',
    'bloodgrp': '+++bloodgrp+++',
    'EmercontactNo': '+++EmercontactNo+++',
}


def getFormWidget(id):
    tup = necdict.get(id, ())
    outdic = {}
    for field in tup:
        if field in widgetDict.keys():
            outdic[field] = widgetDict[field]

    return outdic
